### ISSUE TITLE
issue on the script while trying to check for ATS settings

### ISSUE THREAD

**Issue by sispeo** [codyhosterman/powercli#2]
Hello

while runing the script, it fails at gettings the value for ATS settings
trying to run the command "$esxcli.storage.vmfs.lockmode.list.CreateArgs()"
returns the error 

You cannot call a method on a null-valued expression.
At line:1 char:1
- $esxcli.storage.vmfs.lockmode.list.CreateArgs()
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidOperation: (:) [], RuntimeException
  - FullyQualifiedErrorId : InvokeMethodOnNull

I am runing powercli v6.3 r1 build 3737840
Esxi hosts versions are 5.5.0 build-2302651

Thanks for your help in troubleshooting this

Regards

Philippe

**Comment by cajeeper** [comment]
There's not enough information to determine what the issue is. First of, which script are you running?

**Comment by codyhosterman** [comment]
Let me look into this. I have a thought why this might be happening, but i need to run some tests first. Stay tuned.

**Comment by codyhosterman** [comment]
Okay I think i fixed it. Try the latest version

**Comment by sispeo** [comment]
the fix is working

many thanks for your help

**Comment by codyhosterman** [comment]
Awesome, glad to hear! Thanks for reporting the bug
