### ISSUE TITLE
multiple errors trying to run bestpracticechecker.ps1

### ISSUE THREAD

**Issue by beezel** [codyhosterman/powercli#6]
I'm trying to run your script for the first time in an existing environment, but getting a lot of errors.

Details are: vCenter 6.0, PowerCLI 6.5 R1, PS 5.1

I downloaded your repo directly and have not edited the files (other than renaming bestpracticeschecker.ps1 to Get_Pure_Best_Practices.ps1). Any ideas off the top of your head?

I am getting the following error dump upon execution:

`At C:\scripts\infrastructure\vmware\Get_Pure_Best_Practices.ps1:129 char:104
... s://my.vmware.com/web/vmware/details?downloadGroup=PCLI650R1&productI ...
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.

At C:\scripts\infrastructure\vmware\Get_Pure_Best_Practices.ps1:251 char:123
 ... t for VMs they will not boot unless this is set to 4096 (4 MB) or low ...
Unexpected token 'MB' in expression or statement.

At C:\scripts\infrastructure\vmware\Get_Pure_Best_Practices.ps1:251 char:122
... boot for VMs they will not boot unless this is set to 4096 (4 MB) or  ...
Missing closing ')' in expression.
At C:\scripts\infrastructure\vmware\Get_Pure_Best_Practices.ps1:91 char:9
        {

Missing closing '}' in statement block or type definition.
At C:\scripts\infrastructure\vmware\Get_Pure_Best_Practices.ps1:89 char:5
    {

Missing closing '}' in statement block or type definition.
At C:\scripts\infrastructure\vmware\Get_Pure_Best_Practices.ps1:79 char:142
+ ... ntinue)) -and (!(get-Module -Name VMware.PowerCLI -ListAvailable))) {

Missing closing '}' in statement block or type definition.
At C:\scripts\infrastructure\vmware\Get_Pure_Best_Practices.ps1:251 char:125
...  for VMs they will not boot unless this is set to 4096 (4 MB) or lowe ...

Unexpected token ')' in expression or statement.
At C:\scripts\infrastructure\vmware\Get_Pure_Best_Practices.ps1:282 char:77
... ent $logfile "[****NEEDS ATTENTION****]The VAAI ATOMIC TEST & SET (As ...

The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At C:\scripts\infrastructure\vmware\Get_Pure_Best_Practices.ps1:291 char:129
...  Heartbeating is not configured to use the VAAI ATOMIC TEST & SET (As ...

The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At C:\scripts\infrastructure\vmware\Get_Pure_Best_Practices.ps1:452 char:36
          add-content $logfile "[****NEEDS ATTENTION****]There is m ...

Array index expression is missing or not valid.
Not all parse errors were reported.  Correct the reported errors and try again.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : AmpersandNotAllowed`

**Comment by webmastir** [comment]
Are you sure it's not the same problem as [this comment](https://www.codyhosterman.com/2016/05/updated-flasharray-vmware-best-practices-powercli-scripts/#comment-44897)?

> Looks like you right-clicked on the link in github and saved as ps1. This link actually points to an HTML file, so PowerShell doesnt run. CLick on the link and then choose view raw. Save the raw text (the code) as a ps1 file. 

^Cody's [response](https://www.codyhosterman.com/2016/05/updated-flasharray-vmware-best-practices-powercli-scripts/#comment-44898).

**Comment by beezel** [comment]
Thanks @webmastir , I'd already seen that and though that wasn't my path, it did trigger me to clone this repo and just mv the file with a new name (to fit our conventions). Nothing else has been modified, and I just inspected the ps1 myself and it does not have any HTML or anything else. It starts just as on this git with `<# Optional parameters. Keep these values at default unless necessary and understood`

It is an odd error that I've not seen before, and while I'm new to this environment I've been running many ps scripts with success from this box (it's a tools-type vm).

**Comment by webmastir** [comment]
Yeah...that is strange. I just ran it really quick and didn't have a problem.
```
PS C:\Users\User\Downloads\PureStorage> iwr https://raw.githubusercontent.com/codyhosterman/powercli/master/bestpracticechecker.ps1 -outfile bestpracticechecker.ps1
PS C:\Users\User\Downloads\PureStorage> .\bestpracticechecker.ps1

	Please choose a directory to store the script log

	WARNING: The cmdlet "Get-PowerCLIVersion" is deprecated. Please use the 'Get-Module' cmdlet instead.
	Please enter a vCenter IP or FQDN: 10.110.13.30

	Script result log can be found at C:\Users\User\Downloads\PureStorage\2018-11-07T13.10.44.1816163-06.00checkbestpractices.log

	The default behavior is to check every host in vCenter.
	Would you prefer to limit this to hosts in a specific cluster? (y/n): y
	Please choose the cluster in the dialog box that popped-up.

	Executing...
	Check complete.

	No errors were found.

	Refer to log file for detailed results.
	
PS C:\Users\User\Downloads\PureStorage>
```
Hope you get it figured out, @beezel.

**Comment by beezel** [comment]
Thanks for the confirmation, @webmastir. I ran it on another box and it executed fine, so I have some figuring out to do. I'll close this as it's not a script issue.
