### ISSUE TITLE
Multiple errors running PureStorageVMwareStorageTool.ps1

### ISSUE THREAD

**Issue by dburkland** [codyhosterman/powercli#7]
At Z:\dburkland\Dropbox\Scripts\powershell\PureStorageVMwareStorageTool.ps1:687 char:123
+ ... mdevice.Backing.fileName) ($($vmdevice.CapacityInKB/1024/1024) GB)"))
+                                                                    ~~
Unexpected token 'GB' in expression or statement.
At Z:\dburkland\Dropbox\Scripts\powershell\PureStorageVMwareStorageTool.ps1:687 char:122
+ ... mdevice.Backing.fileName) ($($vmdevice.CapacityInKB/1024/1024) GB)"))
+                                                                   ~
Missing closing ')' in expression.
At Z:\dburkland\Dropbox\Scripts\powershell\PureStorageVMwareStorageTool.ps1:43 char:7
+       {
+       ~
Missing closing '}' in statement block or type definition.
At Z:\dburkland\Dropbox\Scripts\powershell\PureStorageVMwareStorageTool.ps1:41 char:3
+   {
+   ~
Missing closing '}' in statement block or type definition.
At Z:\dburkland\Dropbox\Scripts\powershell\PureStorageVMwareStorageTool.ps1:31 char:142
+ ... ntinue)) -and (!(get-Module -Name VMware.PowerCLI -ListAvailable))) {
+                                                                         ~
Missing closing '}' in statement block or type definition.
At Z:\dburkland\Dropbox\Scripts\powershell\PureStorageVMwareStorageTool.ps1:687 char:125
+ ... mdevice.Backing.fileName) ($($vmdevice.CapacityInKB/1024/1024) GB)"))
+                                                                      ~
Unexpected token ')' in expression or statement.
At Z:\dburkland\Dropbox\Scripts\powershell\PureStorageVMwareStorageTool.ps1:698 char:47
+                   $VMDKDropDownBox.Items.Add("No virtual disks found" ...
+                                               ~~
Unexpected token 'No' in expression or statement.
At Z:\dburkland\Dropbox\Scripts\powershell\PureStorageVMwareStorageTool.ps1:721 char:130
+ ... viceName.substring(14,32)) ($($vmdevice.CapacityInKB/1024/1024) GB)")
+                                                                     ~~
Unexpected token 'GB' in expression or statement.
At Z:\dburkland\Dropbox\Scripts\powershell\PureStorageVMwareStorageTool.ps1:721 char:129
+ ... viceName.substring(14,32)) ($($vmdevice.CapacityInKB/1024/1024) GB)")
+                                                                    ~
Missing closing ')' in expression.
At Z:\dburkland\Dropbox\Scripts\powershell\PureStorageVMwareStorageTool.ps1:721 char:132
+ ... viceName.substring(14,32)) ($($vmdevice.CapacityInKB/1024/1024) GB)")
+                                                                       ~
Unexpected token ')' in expression or statement.
Not all parse errors were reported.  Correct the reported errors and try again.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : UnexpectedToken

**Comment by Janachara** [comment]
Hello!

I receive these same error message when I just copy and paste scrips from each PowerShell script's page on GitHub into my text editor of choice.
I do not receive them when I click the 'Raw' button first, though.

When  you have a minute, maybe try clicking the 'Raw' button first, copy and paste the script from the raw page, and then see if the problem persists?

NOTE:  I don't work for Pure Storage in any capacity.  I'm just a very satisfied customer. :)

**Comment by codyhosterman** [comment]
Thankss @Janachara! Did that help, that would be my guess is what is wrong as well. I have a few issues I am looking at fixing in this tool. Though I am planning on likely retiring it in favor of my PS module I have written

**Comment by ourNCTapps** [comment]
I have having the exact same errors and have tried both a copy and paste in Notepad++ and clicking the RAW button

**Comment by dburkland** [comment]
Same here, tried using Visual Studio Code as well (no luck).

**Comment by codyhosterman** [comment]
So I have figured out the root of this problem, it has to do with formatting when copy/pasting. If you copy it into something like Notepad first, then save it, it works fine. If you paste it directly into VS Code or something that preserves formatting it will fail. I am not quite sure _why_ but this workaround does resolve this issue. 

With that being said using the GitHub tools to clone/download the repo is the best option. Or something like wget to get a single file.
